  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-success fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Corpus'Fit</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/units">Unidades</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Espaço do Cliente</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('https://www.motoringresearch.com/wp-content/uploads/2020/03/shutterstock_721723381.jpg')">
          <div class="carousel-caption d-none d-md-block">
          </div>
        </div>
      </div>
    </div>
  </header>
    <div class="container-fluid">
      <div class ="row">
        <div class="col-md-12">
          <h1 class="my-4">Bem-Vindo a <span class="text-success">Corpus'Fit</span></h1>
        </div>
      </div>
      <!-- Marketing Icons Section -->
      <div class="row">
        <div class="col-md-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://i.imgur.com/oZcR5tI.jpg" alt=""></a>
            <div class="card-body">
              <h4  class="text-success" >Os melhores Profissionais
              </h4><hr>
              <p class="card-text">Temos os mais experientes profissionais para te dar 
              o melhor treino possível</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://i.imgur.com/MGWUQiW.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="text-success" > Os melhores Equipamentos
              </h4><hr>
              <p class="card-text">Apenas o melhor só para vocês!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://i.imgur.com/xEKoBLZ.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="text-success" >Ambiente Climatizado
              </h4><hr>
              <p class="card-text">Qualidade e conforto, 
              vocês quem mandam!</p>
            </div>
          </div>
        </div>
      </div>
      <div class ="row">
        <div class="col-md-12">
          <hr>
          <h2><span class="text-success">Planos</span></h2>
          <h5>Sabemos que quando se trata de preço tudo faz diferença e por conta disso a Corpus'Fit pensou especialmente em você!</h5>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-lg-3 mb-4">
          <div class="card h-100">
            <img class="card-img-top" src="https://i.imgur.com/nlAdAhT.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title"><span class="text-success">Plano Green</span></h4>
              <p class="card-text">Treine em qualquer academia Corpus'Fit do Brasil.<br><hr>
              <p class="card-text"> <h5><span class="text-success">DIFERENCIAIS</span></h5>
              <p>Leve amigos para treinar com você<br></p>
              Cadeira de massagem<br>
              Camiseta Black<br>
              Corpus'Fit Go<br>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-success">APROVEITE</a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 mb-4">
          <div class="card h-100">
            <img class="card-img-top" src="https://i.imgur.com/oNVuc3k.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title"><span class="text-success">Plano Corpus'Fit</span></h4>
              <p class="card-text">Acesso ilimitado a todos os equipamentos, exceto massagem.<br><hr>
              <h5><span class="text-success">DIFERENCIAIS</span></h5>
              Sem taxa de cancelamento<br><br>
              Corpus'Fit Go<br><br>
              <br><br>
              R$70,00
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-success">APROVEITE</a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 mb-4">
          <div class="card h-100">
            <img class="card-img-top" src="https://i.imgur.com/xGEvpuc.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title"><span class="text-success">Plano VIP</span></h4>
              <p class="card-text">Acesso exclusivo as melhores Corpus'Fit do Brasil. <hr><h5><span class="text-success">DIFERENCIAIS</span></h5>
              <p>Leve amigos para treinar com você<br></p>
              Cadeira de massagem<br>
              Camiseta Black<br>
              Corpus'Fit  Go<br>
              Acesso ilimitado a todas áreas da academia<br>
              Área Reservada
              <br> R$ 800,00 / mês
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-success">APROVEITE</a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 mb-4">
          <div class="card h-100">
            <img class="card-img-top" src="https://i.imgur.com/oZcR5tI.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title"><span class="text-success">Plano Anual</span></h4>
              <p class="card-text">Treine em qualquer academia Corpus'Fit do Brasil.<br><hr>
              <h5><span class="text-success">DIFERENCIAIS</span></h5>
              Sem taxa de cancelamento<br><br>
              Corpus'Fit Go<br><br>
              <br><br>
              R$1000,00/ano
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-success">APROVEITE</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <hr>
          <h2 class="text-center fz-32 mb-6">
            Conheça a sua <span class="text-success">nova Corpus'Fit</span>
          </h2>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://cdn.smartfit.com.br/nossa-smart/img_cover_academia_aulas.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
              <span class="text-success">Fit Dance
              </span></h4><hr>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://cdn.smartfit.com.br/nossa-smart/img_cover_academia_musculacao.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
              <span class="text-success">Musculação
              </span></h4><hr>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://cdn.smartfit.com.br/nossa-smart/img_cover_academia_funcional.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
              <span class="text-success">Funcional
              </span></h4><hr>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://cdn.smartfit.com.br/nossa-smart/img_cover_academia_cardio.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
              <span class="text-success">Cardio
              </span></h4><hr>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://cdn.smartfit.com.br/nossa-smart/img_cover_academia_vestiario.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
              <span class="text-success">Vestiário
              </span></h4><hr>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://cdn.smartfit.com.br/nossa-smart/img_cover_academia_armarios.jpg" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
              <span class="text-success">Armários
              </span></h4><hr>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row text-center justify-around" style="margin-top: 35px">
        <div class="col-md-12">
          <h2 class="text-black mb-6 fz-28">
            Vamos vencer <span class="text-success">A COVID-19</span>
          </h2>
          <p class="fz-24 mb-6">
            <strong>Precisamos da sua ajuda</strong>. Só assim, vamos
            conseguir deixar a Corpus'Fit um lugar mais seguro para todos.
          </p>
          <h1 class="font-weight-bold mb-6"><span class="text-success">Mudanças importantes</span></h1>
          <div class="row" style="margin-top: 35px">
            <div class="col-md-2">
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title"><span class="text-success">Desinfecção completa</span></h5><hr>
                  <br><img class="card-img-top" src="https://i.imgur.com/nHShQCN.png" height="20%" width="40%" alt="">
                   <br><br>
                   <h6 class="card-text">Desinfectamos todas as academias com <strong>aparelho nebulizador</strong> de 2 a 3 vezes por dia.</h6>
                   <hr>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <div class="card h-100">
                <div class="card-body">
                  <h6 class="card-title"><span class="text-success">Distância entre aparelhos</span></h6><hr><br>
                  <img class="card-img-top" src="https://i.imgur.com/aJi9fi9.png" height="20%" width="40%" alt="">
                  <br><br>
                  <h6 class="card-text">Desativamos metade dos aparelhos de cardio para manter uma <strong>distância segura </strong>entre os clientes.</h6>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title"><span class="text-success">Agende seu horário</span></h5>  <hr><br>
                  <img class="card-img-top" src="https://i.imgur.com/qWMB2RD.png" height="20%" width="40%" alt=""><br><br>
                  <h6 class="card-text">Vamos evitar aglomeração. Antes de ir à academia, <strong>Agende seu horário. </strong></h6><br>
                  <hr>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title"><span class="text-success">Termômetro digital</span></h5><hr><br>
                  <img class="card-img-top" src="https://i.imgur.com/skoYEL4.png" height="20%" width="40%" alt=""><br>
                  <h6 class="card-text">Vamos medir sua temperatura na recepção.<strong>Se estiver acima de 37,8º C, </strong>volte para casa por favor</h6><br>
                  <hr>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <div class="card h-100">
                <div class="card-body">
                  <h6 class="card-title"><span class="text-success">Uso de Máscaras</span></h6><hr><br>
                  <img class="card-img-top" src="https://i.imgur.com/KhP6eDP.png" height="20%" width="40%" alt=""><br>
                  <br><br>
                  <h6 class="card-text">A máscara é obrigatória.<strong>Toda nossa equipe usará máscaras, </strong>assim como os alunos.</h6>
                  <hr>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title"><span class="text-success">Tapetes de Higienização</span></h5><hr><br>
                  <img class="card-img-top" src="https://i.imgur.com/LXQhHRy.png" height="20%" width="40%" alt=""><br>
                  <br><br>
                  <h6 class="card-text">Temos tapetes na entrada para você <strong>higienizar seus tênis.</strong></h6><br><br>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div> 
      </div>
      <div class="row" style="margin-top: 35px">
        <div class="col-md-12">
          <div class="card-group">
            <div class="card">
              <div class="card-body">
                <h2 class="card-title">Use <span class="text-success">máscara</span></h2><hr>
                <h5 class="card-text">É obrigatório usar máscara. Cubra o nariz, a boca e o queixo para evitar as gotículas de saliva</h5>
              </div>
            </div>
            <div class="col-md-4 card">
              <div class="card-body">
                <h2 class="card-title">Leve <span class="text-success">água</span></h2><hr>
                <h5 class="card-text">Não se esqueça da garrafinha com água. Nem toda cidade tem liberação para usar bebedouros</h5>
              </div>
            </div>
            <div class="card">
              <div class="card-body">
                <h2 class="card-title">Álcool<span class="text-success"> a 70%</span></h2><hr>
                <h5 class="card-text"> Temos álcool a 70% em todas as áreas da academia para você higienizar as mãos</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="py-5 bg-dark" style="margin-top: 35px">
      <div class="container-fluid">
        <div class ="row"><div class="col-md-12"><h5 class="m-0 text-center text-success">Desenvolvido por: </h5><hr></div></div>
        <div class="row text-center text-white">
          <div class="col-lg-3">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="https://p7.hiclipart.com/preview/609/846/439/discord-computer-icons-logo-computer-software-avatar.jpg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777" src=""></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
            <h3>Emmanuel</h3>
            <p class="text-white">Matricula: 202001566211</p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-3">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
            <h3>Leonardi</h3>
            <p class="text-white">Matricula:201908278692 </p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-3">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
            <h3>Pedro Henrique</h3>
            <p class="text-white">Matricula: 202002564695</p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-3">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
            <h3>Yan</h3>
            <p class="text-white">Matricula: 202004266853</p>
          </div>
        </div>
        <p style="margin:4px 0 -4% 0">2020 Estácio</p>
      </div>
    </footer>