  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-success fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Corpus'Fit</a>
        </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/units">Unidades</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/login">Espaço do Cliente</a>
                            </li>

                     </ul>
                </div>
      </div>
  </nav>

    <main role="main">
        <section class="jumbotron text-center">
            <div class="container">
                <h1><span class="text-success">Nossas Localizações</span>
                </h1>
                    <p class="lead text-muted">São mais de 541 Corpus'Fit pensadas exatamente no seu conforto e na sua comodidade.</p>
                        <a href="cadastro.html" class="btn btn-success my-2">Fazer Matricula</a>
                        <a href="index.html" class="btn btn-secondary my-2">Página Inicial</a>
            </div>
        </section>
    </main>


  <div class="album py-5 bg-light">
      <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="https://s3.amazonaws.com/smartsystem/pictures/4694/big/smart-fit-academia-asa_norte_i-df-area-cardiovascular-transport-eliptico.jpg?1543233378" data-holder-rendered="true">
                        <div class="card-body"><h5>Shoppig Grande Rio</h5><hr>
                            <p class="card-text">Avenida Benjamin Pinto Dias, 1130 - Vila Dagmar
                                Belford Roxo, RJ - 2613017
                            </p>
                        </div>
              </div>
            </div>

              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/5006/big/smart-fit-academia-unidade-asa-norte-iv-df-1-equipamento-area-smart_shape-airbike-circuito_de_emagrecimento-condicionamento.jpg?1540231241" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                        <div class="card-body"><h5>Queimados</h5><hr>
                            <p class="card-text"></p>
                                <p class="card-text">Avenida Olímpia Silva, 740 - Pacaembu
                                    Queimados, RJ - 26325370
                                </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                        </div>
                                    </div>
                        </div>
              </div>
            </div>

              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/4945/big/smart-fit-academia-unidade-asa-sul-3-df-equipamentos-area-aulas_de_ginastica-zumba-shbam-fit_dance-abdominal-alongamento-body_balance.png?1536943607" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                        <div class="card-body"><h5>Mário Guimarães</h5><hr>
                            <p class="card-text">Avenida Doutor Mário Guimarães, 638 - Centro
                                Nova Iguaçu, RJ - 26255230
                            </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>
                                </div>
                        </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/7791/big/720x640_QueBom_NDA_02.png?1594061406" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                        <div class="card-body"><h5>Via Light</h5><hr>
                            <p class="card-text">Rua Arcelino Pereira Neves, 351 - Centro
                                Nova Iguaçu, RJ - 26220010
                            </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>
                                </div>
                        </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/5003/big/smart-fit-academia-unidade-sig-df-1-equipamento-area-smart_shape-airbike-circuito_de_emagrecimento-condicionamento.jpg?1540232266" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                        <div class="card-body"><h5>Shopping Grande Rio</h5><hr>
                            <p class="card-text">Rua Maria Soares Sendas, 111 - Parque Barreto
                                São João de Meriti, RJ - 25575825
                            </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>
                                </div>
                        </div>
                </div>
            </div>

              <div class="col-md-4">
                  <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/2174/big/sudoeste-i-1.jpg?1428290112" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                        <div class="card-body"><h5>Vilar dos Teles</h5><hr>
                            <p class="card-text">Av. Automóvel Clube, 2487 - Vilar dos Teles
                                São João de Meriti, RJ - 25565171
                            </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>
                                </div>
                        </div>
                  </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/2376/big/asa-norte-ii-5.jpg?1428291085" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                    <div class="card-body"><h5>Duque de Caxias</h5><hr>
                        <p class="card-text">R. Professor José de Souza, 1216 - Jardim Vinte e Cinco de Agosto
                            Duque de Caxias, RJ - 25071202
                        </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">

                                </div>
                            </div>
                    </div>
                </div>
            </div>

              <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/6694/big/smart-fit-515-norte-sala-de-ginastica.jpg?1599583119" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                            <div class="card-body"><h5>Guadalupe</h5><hr>
                                <p class="card-text">Av. Brasil, 22.155 - Guadalupe
                                    Rio de Janeiro, RJ - 21670000
                                </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">

                                        </div>
                                    </div>
                            </div>
                    </div>
              </div>
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="https://s3.amazonaws.com/smartsystem/pictures/4694/big/smart-fit-academia-asa_norte_i-df-area-cardiovascular-transport-eliptico.jpg?1543233378" data-holder-rendered="true" style="height: 225px; width: 100%; display: block;">
                        <div class="card-body"><h5>Carioca Shopping</h5><hr>
                            <p class="card-text">Avenida Vicente de Carvalho, 909 - Vila da Penha
                                Rio de Janeiro, RJ - 21210623
                            </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>
                                </div>
                        </div>
                </div>
            </div>
          </div>
      </div>
  </div>